# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Go Module tcr-engine
  - package-ecosystem: "gomod"
    directory: "/tcr-engine"
    schedule:
      interval: "daily"

  # Maintain dependencies for Go Module tcr-cli
  - package-ecosystem: "gomod"
    directory: "/tcr-cli"
    schedule:
      interval: "daily"

  # Maintain dependencies for Go Module tcr-gui
  - package-ecosystem: "gomod"
    directory: "/tcr-gui"
    schedule:
      interval: "daily"

  # Maintain dependencies for Go Module tcr-doc
  - package-ecosystem: "gomod"
    directory: "/tcr-doc"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven in testsdata/java
  - package-ecosystem: "maven"
    directory: "/tcr-engine/testdata/java"
    schedule:
      interval: "daily"

  # Maintain dependencies for gradle in testsdata/java
  - package-ecosystem: "gradle"
    directory: "/tcr-engine/testdata/java"
    schedule:
      interval: "daily"

  # Maintain dependencies for go modules in testsdata/go
  - package-ecosystem: "gomod"
    directory: "/tcr-engine/testdata/go"
    schedule:
      interval: "daily"

  # Maintain dependencies for Nuget in testsdata/csharp
  - package-ecosystem: "gomod"
    directory: "/tcr-engine/testdata/csharp"
    schedule:
      interval: "daily"
      