linters:
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
  disable:
    - goimports
    - errcheck
    - revive
run:
  go: "1.18"
  timeout: 5m
  skip-dirs:
    - testdata
    - build
    - _test_results
  skip-files:
    - .*generated.*
linters-settings:
  gocyclo:
    min-complexity: 16
  govet:
    check-shadowing: false
  lll:
    line-length: 200
  nakedret:
    command: nakedret
    pattern: ^(?P<path>.*?\\.go):(?P<line>\\d+)\\s*(?P<message>.*)$
issues:
  # The default exclusion rules are a bit too permissive, so copying the relevant ones below
  exclude-use-default: false
  exclude:
    - parameter .* always receives
