# This is goreleaser configuration for releasing tcr-cli application.
# Make sure to check the documentation at http://goreleaser.com
project_name: tcr
before:
  hooks:
    - make tidy
builds:
  - id: "tcr-cli"
    dir: tcr-cli
    binary: tcr
    ldflags:
      - -s -w
      - -X github.com/murex/tcr-engine/settings.BuildVersion={{.Version}}
      - -X github.com/murex/tcr-engine/settings.BuildOs={{.Os}}
      - -X github.com/murex/tcr-engine/settings.BuildArch={{.Arch}}
      - -X github.com/murex/tcr-engine/settings.BuildCommit={{.Commit}}
      - -X github.com/murex/tcr-engine/settings.BuildDate={{.Date}}
      - -X github.com/murex/tcr-engine/settings.BuildAuthor=goreleaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'