# This is goreleaser configuration for releasing tcr-cli application.
# Make sure to check the documentation at http://goreleaser.com
project_name: tcr
before:
  hooks:
    - make tidy
builds:
  - id: "tcr-cli"
    dir: tcr-cli
    binary: tcr
    env:
      - CGO_ENABLED=0
      - CONFIG_PKG=github.com/murex/tcr/tcr-engine/config
    ldflags:
      - -s -w
      - -X {{.Env.CONFIG_PKG}}.BuildVersion={{.Version}}
      - -X {{.Env.CONFIG_PKG}}.BuildOs={{.Os}}
      - -X {{.Env.CONFIG_PKG}}.BuildArch={{.Arch}}
      - -X {{.Env.CONFIG_PKG}}.BuildCommit={{.Commit}}
      - -X {{.Env.CONFIG_PKG}}.BuildDate={{.Date}}
      - -X {{.Env.CONFIG_PKG}}.BuildAuthor=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'