name: Go lint
on:
  push:
    tags:
      - v*
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    name: lint
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45
          # Optional: working directory, useful for mono-repos
          working-directory: src

          # Optional: golangci-lint command line arguments.
          args: --build-tags=test_helper

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
