name: Go lint
on:
  push:
    tags:
      - v*
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install CGO Libraries
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.44
          # Optional: working directory, useful for mono-repos
          working-directory: tcr-cli

          # Optional: golangci-lint command line arguments.
          args: --build-tags=test_helper

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
